// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriWise.Infrastructure.Database;

#nullable disable

namespace NutriWise.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergyUserProfile", b =>
                {
                    b.Property<Guid>("AllergiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("AllergiesId", "UserProfilesId");

                    b.HasIndex("UserProfilesId");

                    b.ToTable("AllergyUserProfile", (string)null);
                });

            modelBuilder.Entity("KitchenEquipmentUserProfile", b =>
                {
                    b.Property<Guid>("KitchenEquipmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("KitchenEquipmentsId", "UserProfilesId");

                    b.HasIndex("UserProfilesId");

                    b.ToTable("KitchenEquipmentUserProfile", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Product.FoodCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = new Guid("8ed34f48-c691-4f89-948c-ecb2c030e007"),
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = new Guid("01361a54-ee90-42a2-93cd-818806cdac5f"),
                            Name = "Meats"
                        },
                        new
                        {
                            Id = new Guid("6ca09620-d412-44be-ba02-17134db28a98"),
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = new Guid("36e9c5ce-690f-4587-8b59-cf1e42e027db"),
                            Name = "Grains and Legumes"
                        },
                        new
                        {
                            Id = new Guid("513862b9-95a3-4001-a378-b38572a29fde"),
                            Name = "Nuts and Seeds"
                        },
                        new
                        {
                            Id = new Guid("badeac32-9693-444f-9d72-52dc2929dccb"),
                            Name = "Oils and Fats"
                        },
                        new
                        {
                            Id = new Guid("171854e3-6862-4dda-892e-f72bed876606"),
                            Name = "Herbs and Spices"
                        },
                        new
                        {
                            Id = new Guid("700b0bbd-f843-4d0e-96c8-39edf19e1fa1"),
                            Name = "Baking Ingredients"
                        });
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Product.FoodSubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodSubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dede805-7bf7-4055-8a8c-2917b2f859c2"),
                            CategoryId = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Citrus Fruits"
                        },
                        new
                        {
                            Id = new Guid("d6d9fe22-f9bc-4617-ba86-a09ac8c97af0"),
                            CategoryId = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Berries"
                        },
                        new
                        {
                            Id = new Guid("70330ebb-02af-4984-b42b-75a5ce2a4232"),
                            CategoryId = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Stone Fruits"
                        },
                        new
                        {
                            Id = new Guid("489fc833-6d06-4277-a241-0e9a70926123"),
                            CategoryId = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Tropical Fruits"
                        },
                        new
                        {
                            Id = new Guid("04b663f0-fe68-46a5-8099-b7d89efbdb98"),
                            CategoryId = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Pome Fruits"
                        },
                        new
                        {
                            Id = new Guid("66bb930f-d411-4b60-a024-7d1ccaa1314a"),
                            CategoryId = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Melons"
                        },
                        new
                        {
                            Id = new Guid("dbad3ebe-f187-44ab-b5e9-58bbb9ad2630"),
                            CategoryId = new Guid("88414907-d38c-40e6-96f3-b82fed911250"),
                            Name = "Dried Fruits"
                        },
                        new
                        {
                            Id = new Guid("0fe90c47-53ab-4893-9832-53382454283d"),
                            CategoryId = new Guid("8ed34f48-c691-4f89-948c-ecb2c030e007"),
                            Name = "Leafy Greens"
                        },
                        new
                        {
                            Id = new Guid("adb0c96f-7779-44ff-8160-556d7c63be61"),
                            CategoryId = new Guid("8ed34f48-c691-4f89-948c-ecb2c030e007"),
                            Name = "Cruciferous Vegetables"
                        },
                        new
                        {
                            Id = new Guid("e775aa73-985c-4198-ac6d-0c19f6e191e8"),
                            CategoryId = new Guid("8ed34f48-c691-4f89-948c-ecb2c030e007"),
                            Name = "Root Vegetables"
                        },
                        new
                        {
                            Id = new Guid("41702ab8-15c4-49b3-9201-387f1e143111"),
                            CategoryId = new Guid("8ed34f48-c691-4f89-948c-ecb2c030e007"),
                            Name = "Allium Vegetables"
                        },
                        new
                        {
                            Id = new Guid("3e2eed01-e879-4dee-beb4-e9338400a6fd"),
                            CategoryId = new Guid("8ed34f48-c691-4f89-948c-ecb2c030e007"),
                            Name = "Squash Vegetables"
                        },
                        new
                        {
                            Id = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f"),
                            CategoryId = new Guid("8ed34f48-c691-4f89-948c-ecb2c030e007"),
                            Name = "Nightshades"
                        },
                        new
                        {
                            Id = new Guid("9d7fff01-9e87-436d-9761-bfcc9cc4ad5a"),
                            CategoryId = new Guid("01361a54-ee90-42a2-93cd-818806cdac5f"),
                            Name = "Beef"
                        },
                        new
                        {
                            Id = new Guid("ac14dc1d-fa3c-4e9f-bdc8-62ad10b687c7"),
                            CategoryId = new Guid("01361a54-ee90-42a2-93cd-818806cdac5f"),
                            Name = "Pork"
                        },
                        new
                        {
                            Id = new Guid("1c9f7178-9f48-4383-a7d8-52b3c4a2eba5"),
                            CategoryId = new Guid("01361a54-ee90-42a2-93cd-818806cdac5f"),
                            Name = "Poultry"
                        },
                        new
                        {
                            Id = new Guid("317cabed-f827-4117-88ab-579730269b54"),
                            CategoryId = new Guid("01361a54-ee90-42a2-93cd-818806cdac5f"),
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("1b26e890-6f81-4e22-9763-301ff482e6f3"),
                            CategoryId = new Guid("01361a54-ee90-42a2-93cd-818806cdac5f"),
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc"),
                            CategoryId = new Guid("6ca09620-d412-44be-ba02-17134db28a98"),
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("f8ccc5ab-4e8e-4be9-9978-747aa19968eb"),
                            CategoryId = new Guid("6ca09620-d412-44be-ba02-17134db28a98"),
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("5bdf8914-ba06-4415-b018-09a41edf26fd"),
                            CategoryId = new Guid("6ca09620-d412-44be-ba02-17134db28a98"),
                            Name = "Other Dairy"
                        },
                        new
                        {
                            Id = new Guid("4f55fb5c-7117-4911-b481-48a75141c85e"),
                            CategoryId = new Guid("36e9c5ce-690f-4587-8b59-cf1e42e027db"),
                            Name = "Rice"
                        },
                        new
                        {
                            Id = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37"),
                            CategoryId = new Guid("36e9c5ce-690f-4587-8b59-cf1e42e027db"),
                            Name = "Other Grains"
                        },
                        new
                        {
                            Id = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c"),
                            CategoryId = new Guid("36e9c5ce-690f-4587-8b59-cf1e42e027db"),
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = new Guid("f5d6dae7-80a7-45ec-8995-cbe47452a12b"),
                            CategoryId = new Guid("36e9c5ce-690f-4587-8b59-cf1e42e027db"),
                            Name = "Legumes"
                        },
                        new
                        {
                            Id = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b"),
                            CategoryId = new Guid("513862b9-95a3-4001-a378-b38572a29fde"),
                            Name = "Nuts"
                        },
                        new
                        {
                            Id = new Guid("8378c940-b7ee-41a0-b740-fc7dcb62729d"),
                            CategoryId = new Guid("513862b9-95a3-4001-a378-b38572a29fde"),
                            Name = "Seeds"
                        },
                        new
                        {
                            Id = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f"),
                            CategoryId = new Guid("badeac32-9693-444f-9d72-52dc2929dccb"),
                            Name = "Oils"
                        },
                        new
                        {
                            Id = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8"),
                            CategoryId = new Guid("171854e3-6862-4dda-892e-f72bed876606"),
                            Name = "Herbs"
                        },
                        new
                        {
                            Id = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28"),
                            CategoryId = new Guid("171854e3-6862-4dda-892e-f72bed876606"),
                            Name = "Spices"
                        },
                        new
                        {
                            Id = new Guid("d133f302-ec57-4acb-845c-eb0daea1b6de"),
                            CategoryId = new Guid("700b0bbd-f843-4d0e-96c8-39edf19e1fa1"),
                            Name = "Sugars"
                        },
                        new
                        {
                            Id = new Guid("fb7a6e78-1351-4992-a732-1b4f8510dcb9"),
                            CategoryId = new Guid("700b0bbd-f843-4d0e-96c8-39edf19e1fa1"),
                            Name = "Baking Ingredients"
                        });
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Calories")
                        .HasColumnType("double precision");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<double?>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Fats")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Proteins")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("be386ce9-642f-4eae-9216-9929dd40d494"),
                            Caption = "Oranges",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4dede805-7bf7-4055-8a8c-2917b2f859c2")
                        },
                        new
                        {
                            Id = new Guid("51bc7ce0-2d13-453f-95f8-c1ab94863e24"),
                            Caption = "Lemons",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4dede805-7bf7-4055-8a8c-2917b2f859c2")
                        },
                        new
                        {
                            Id = new Guid("07627bd4-c8b3-4424-b86a-ed9aa3b8b705"),
                            Caption = "Limes",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4dede805-7bf7-4055-8a8c-2917b2f859c2")
                        },
                        new
                        {
                            Id = new Guid("bed632cc-9a10-48e7-8e18-aada96787094"),
                            Caption = "Grapefruits",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4dede805-7bf7-4055-8a8c-2917b2f859c2")
                        },
                        new
                        {
                            Id = new Guid("12ce6a22-aaea-4195-8fc9-fbe191942458"),
                            Caption = "Tangerines",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4dede805-7bf7-4055-8a8c-2917b2f859c2")
                        },
                        new
                        {
                            Id = new Guid("5a672907-c342-436e-8502-3e0d97031ae6"),
                            Caption = "Clementines",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4dede805-7bf7-4055-8a8c-2917b2f859c2")
                        },
                        new
                        {
                            Id = new Guid("5d7ac8fd-919e-415f-91b1-ab35b5f9e755"),
                            Caption = "Strawberries",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d6d9fe22-f9bc-4617-ba86-a09ac8c97af0")
                        },
                        new
                        {
                            Id = new Guid("3686fa0d-f914-405e-9fe7-103950b0e786"),
                            Caption = "Blueberries",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d6d9fe22-f9bc-4617-ba86-a09ac8c97af0")
                        },
                        new
                        {
                            Id = new Guid("a1e3b7a4-a6b0-41e2-b06f-4883d02cc8bb"),
                            Caption = "Raspberries",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d6d9fe22-f9bc-4617-ba86-a09ac8c97af0")
                        },
                        new
                        {
                            Id = new Guid("62119bdf-fd55-469b-89db-6d0d57a22836"),
                            Caption = "Blackberries",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d6d9fe22-f9bc-4617-ba86-a09ac8c97af0")
                        },
                        new
                        {
                            Id = new Guid("7b3846da-8afc-41a9-b1c6-6f4869da8401"),
                            Caption = "Cranberries",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d6d9fe22-f9bc-4617-ba86-a09ac8c97af0")
                        },
                        new
                        {
                            Id = new Guid("46b6dcd7-7e68-4fd5-8c9d-b6c083a319d6"),
                            Caption = "Peaches",
                            IsDeleted = false,
                            SubCategoryId = new Guid("70330ebb-02af-4984-b42b-75a5ce2a4232")
                        },
                        new
                        {
                            Id = new Guid("8e278c30-c879-43ec-b285-0ccd68fc46d9"),
                            Caption = "Plums",
                            IsDeleted = false,
                            SubCategoryId = new Guid("70330ebb-02af-4984-b42b-75a5ce2a4232")
                        },
                        new
                        {
                            Id = new Guid("a97100ab-4039-4ed7-ac79-dc9e7ee26bc0"),
                            Caption = "Cherries",
                            IsDeleted = false,
                            SubCategoryId = new Guid("70330ebb-02af-4984-b42b-75a5ce2a4232")
                        },
                        new
                        {
                            Id = new Guid("709ef077-306e-4ad1-8186-2b142db75fa9"),
                            Caption = "Apricots",
                            IsDeleted = false,
                            SubCategoryId = new Guid("70330ebb-02af-4984-b42b-75a5ce2a4232")
                        },
                        new
                        {
                            Id = new Guid("a024793f-c793-4e0c-9e82-849bc82c70fe"),
                            Caption = "Nectarines",
                            IsDeleted = false,
                            SubCategoryId = new Guid("70330ebb-02af-4984-b42b-75a5ce2a4232")
                        },
                        new
                        {
                            Id = new Guid("bdd7addd-ec15-4589-b19b-c6cf3e460bc3"),
                            Caption = "Bananas",
                            IsDeleted = false,
                            SubCategoryId = new Guid("489fc833-6d06-4277-a241-0e9a70926123")
                        },
                        new
                        {
                            Id = new Guid("de5903e8-58f8-4fd4-9892-ed3e48194c4d"),
                            Caption = "Pineapples",
                            IsDeleted = false,
                            SubCategoryId = new Guid("489fc833-6d06-4277-a241-0e9a70926123")
                        },
                        new
                        {
                            Id = new Guid("fad5c8fe-afe8-4793-8393-3b4700675166"),
                            Caption = "Mangoes",
                            IsDeleted = false,
                            SubCategoryId = new Guid("489fc833-6d06-4277-a241-0e9a70926123")
                        },
                        new
                        {
                            Id = new Guid("70d8eb5d-3775-41d3-ab43-59e2fd15333a"),
                            Caption = "Papayas",
                            IsDeleted = false,
                            SubCategoryId = new Guid("489fc833-6d06-4277-a241-0e9a70926123")
                        },
                        new
                        {
                            Id = new Guid("c16838cc-8cf0-4669-8b8c-36113a7bb1bb"),
                            Caption = "Passion Fruit",
                            IsDeleted = false,
                            SubCategoryId = new Guid("489fc833-6d06-4277-a241-0e9a70926123")
                        },
                        new
                        {
                            Id = new Guid("1ce1be95-65d8-485f-adef-059f2aa90f72"),
                            Caption = "Guavas",
                            IsDeleted = false,
                            SubCategoryId = new Guid("489fc833-6d06-4277-a241-0e9a70926123")
                        },
                        new
                        {
                            Id = new Guid("d48adc0d-f709-405e-a907-ddc7ad9ff580"),
                            Caption = "Apples",
                            IsDeleted = false,
                            SubCategoryId = new Guid("04b663f0-fe68-46a5-8099-b7d89efbdb98")
                        },
                        new
                        {
                            Id = new Guid("00f02108-ed3c-405c-b40c-81794fa386dc"),
                            Caption = "Pears",
                            IsDeleted = false,
                            SubCategoryId = new Guid("04b663f0-fe68-46a5-8099-b7d89efbdb98")
                        },
                        new
                        {
                            Id = new Guid("86f6a723-d3f7-4fcf-83d0-18dae9c37b90"),
                            Caption = "Quinces",
                            IsDeleted = false,
                            SubCategoryId = new Guid("04b663f0-fe68-46a5-8099-b7d89efbdb98")
                        },
                        new
                        {
                            Id = new Guid("35b471fd-0a2b-4244-8ad7-ea90b49513d5"),
                            Caption = "Watermelons",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66bb930f-d411-4b60-a024-7d1ccaa1314a")
                        },
                        new
                        {
                            Id = new Guid("3b3af4ce-8cfb-402c-8473-c4249f07fcf9"),
                            Caption = "Cantaloupes",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66bb930f-d411-4b60-a024-7d1ccaa1314a")
                        },
                        new
                        {
                            Id = new Guid("e53d27bd-1072-4657-8c17-66fb93ff5a1d"),
                            Caption = "Honeydews",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66bb930f-d411-4b60-a024-7d1ccaa1314a")
                        },
                        new
                        {
                            Id = new Guid("6786750d-3d25-4450-a32a-c39f32d85689"),
                            Caption = "Raisins",
                            IsDeleted = false,
                            SubCategoryId = new Guid("dbad3ebe-f187-44ab-b5e9-58bbb9ad2630")
                        },
                        new
                        {
                            Id = new Guid("ab8b1aaf-f5c8-464c-ba94-5be1ebc63556"),
                            Caption = "Dates",
                            IsDeleted = false,
                            SubCategoryId = new Guid("dbad3ebe-f187-44ab-b5e9-58bbb9ad2630")
                        },
                        new
                        {
                            Id = new Guid("73917240-0786-49e3-be6b-b5c16de4be7e"),
                            Caption = "Dried Apricots",
                            IsDeleted = false,
                            SubCategoryId = new Guid("dbad3ebe-f187-44ab-b5e9-58bbb9ad2630")
                        },
                        new
                        {
                            Id = new Guid("99c4c2d5-27aa-4081-ab23-69bef8660a2b"),
                            Caption = "Lettuce",
                            IsDeleted = false,
                            SubCategoryId = new Guid("0fe90c47-53ab-4893-9832-53382454283d")
                        },
                        new
                        {
                            Id = new Guid("f74eb9f5-351e-4126-9d8e-2251d8e4b090"),
                            Caption = "Spinach",
                            IsDeleted = false,
                            SubCategoryId = new Guid("0fe90c47-53ab-4893-9832-53382454283d")
                        },
                        new
                        {
                            Id = new Guid("198bfd3c-43c9-4727-bbe0-45949844a77c"),
                            Caption = "Kale",
                            IsDeleted = false,
                            SubCategoryId = new Guid("0fe90c47-53ab-4893-9832-53382454283d")
                        },
                        new
                        {
                            Id = new Guid("6318144e-27e9-4761-97d5-fa36c5b71e21"),
                            Caption = "Swiss Chard",
                            IsDeleted = false,
                            SubCategoryId = new Guid("0fe90c47-53ab-4893-9832-53382454283d")
                        },
                        new
                        {
                            Id = new Guid("de34a5eb-212a-4400-a2c7-d09b9d7d4529"),
                            Caption = "Arugula",
                            IsDeleted = false,
                            SubCategoryId = new Guid("0fe90c47-53ab-4893-9832-53382454283d")
                        },
                        new
                        {
                            Id = new Guid("4ef91f6c-9814-4724-a218-2b9b2579e261"),
                            Caption = "Broccoli",
                            IsDeleted = false,
                            SubCategoryId = new Guid("adb0c96f-7779-44ff-8160-556d7c63be61")
                        },
                        new
                        {
                            Id = new Guid("300de9fa-d63e-495b-84b0-1c88a99fae4b"),
                            Caption = "Cauliflower",
                            IsDeleted = false,
                            SubCategoryId = new Guid("adb0c96f-7779-44ff-8160-556d7c63be61")
                        },
                        new
                        {
                            Id = new Guid("1b3e0011-16aa-4504-a64e-10e3d3c1572b"),
                            Caption = "Cabbage",
                            IsDeleted = false,
                            SubCategoryId = new Guid("adb0c96f-7779-44ff-8160-556d7c63be61")
                        },
                        new
                        {
                            Id = new Guid("1646be14-9192-4d6e-a151-5d11e48a6388"),
                            Caption = "Brussels Sprouts",
                            IsDeleted = false,
                            SubCategoryId = new Guid("adb0c96f-7779-44ff-8160-556d7c63be61")
                        },
                        new
                        {
                            Id = new Guid("677f02db-e080-47ae-a493-cbb31eef7998"),
                            Caption = "Bok Choy",
                            IsDeleted = false,
                            SubCategoryId = new Guid("adb0c96f-7779-44ff-8160-556d7c63be61")
                        },
                        new
                        {
                            Id = new Guid("20a4aa50-974f-4cbc-82d0-5e935120e6f4"),
                            Caption = "Carrots",
                            IsDeleted = false,
                            SubCategoryId = new Guid("e775aa73-985c-4198-ac6d-0c19f6e191e8")
                        },
                        new
                        {
                            Id = new Guid("2aab4691-567e-4c59-bd19-07c4743db685"),
                            Caption = "Beets",
                            IsDeleted = false,
                            SubCategoryId = new Guid("e775aa73-985c-4198-ac6d-0c19f6e191e8")
                        },
                        new
                        {
                            Id = new Guid("35077c22-72fe-4f9f-bcda-97b078fad89d"),
                            Caption = "Turnips",
                            IsDeleted = false,
                            SubCategoryId = new Guid("e775aa73-985c-4198-ac6d-0c19f6e191e8")
                        },
                        new
                        {
                            Id = new Guid("0ecade65-8777-43b9-a02e-be5ea9b9b971"),
                            Caption = "Radishes",
                            IsDeleted = false,
                            SubCategoryId = new Guid("e775aa73-985c-4198-ac6d-0c19f6e191e8")
                        },
                        new
                        {
                            Id = new Guid("59336075-7dc7-4a95-937f-2e3bd18090e4"),
                            Caption = "Parsnips",
                            IsDeleted = false,
                            SubCategoryId = new Guid("e775aa73-985c-4198-ac6d-0c19f6e191e8")
                        },
                        new
                        {
                            Id = new Guid("c49233f6-8e52-47e6-b6aa-0154e6761197"),
                            Caption = "Onions",
                            IsDeleted = false,
                            SubCategoryId = new Guid("41702ab8-15c4-49b3-9201-387f1e143111")
                        },
                        new
                        {
                            Id = new Guid("6ec66918-dcf6-4492-a145-98f785f73be0"),
                            Caption = "Garlic",
                            IsDeleted = false,
                            SubCategoryId = new Guid("41702ab8-15c4-49b3-9201-387f1e143111")
                        },
                        new
                        {
                            Id = new Guid("7f7abaf0-f21b-4958-8999-d659d8681d70"),
                            Caption = "Leeks",
                            IsDeleted = false,
                            SubCategoryId = new Guid("41702ab8-15c4-49b3-9201-387f1e143111")
                        },
                        new
                        {
                            Id = new Guid("8bcf12ae-8f9a-4306-ba5e-82a59a5aecef"),
                            Caption = "Shallots",
                            IsDeleted = false,
                            SubCategoryId = new Guid("41702ab8-15c4-49b3-9201-387f1e143111")
                        },
                        new
                        {
                            Id = new Guid("d404afd0-b8e2-48d0-bdcb-92729277ee68"),
                            Caption = "Green Onions",
                            IsDeleted = false,
                            SubCategoryId = new Guid("41702ab8-15c4-49b3-9201-387f1e143111")
                        },
                        new
                        {
                            Id = new Guid("d3aab5f9-4e12-44ea-8abd-1102d0157a6d"),
                            Caption = "Zucchini",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3e2eed01-e879-4dee-beb4-e9338400a6fd")
                        },
                        new
                        {
                            Id = new Guid("9c158aa8-57f6-4338-ac7f-d2371cc2c41f"),
                            Caption = "Yellow Squash",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3e2eed01-e879-4dee-beb4-e9338400a6fd")
                        },
                        new
                        {
                            Id = new Guid("c205f15e-4949-4f40-b52f-76dd91f5030d"),
                            Caption = "Pumpkin",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3e2eed01-e879-4dee-beb4-e9338400a6fd")
                        },
                        new
                        {
                            Id = new Guid("b724f9f3-a213-4d03-b41f-c29827cc5c91"),
                            Caption = "Butternut Squash",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3e2eed01-e879-4dee-beb4-e9338400a6fd")
                        },
                        new
                        {
                            Id = new Guid("8baa1731-add6-4fd0-8c41-04a7dd3dd5fe"),
                            Caption = "Acorn Squash",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3e2eed01-e879-4dee-beb4-e9338400a6fd")
                        },
                        new
                        {
                            Id = new Guid("2869c4bf-8f9d-409d-bb1a-0e957d059674"),
                            Caption = "Tomatoes",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("e66b77e6-db6f-4dd6-8e7d-e4b74100859a"),
                            Caption = "Cherry Tomatoes",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("0f62142f-a12c-45fc-af05-0a7b1f8f0e57"),
                            Caption = "Grape Tomatoes",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("f4f4d318-b6ba-425d-99a9-3b4d456cee33"),
                            Caption = "Eggplants",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("5e024ce1-230f-48df-9b0b-acf5f666e548"),
                            Caption = "Bell Peppers",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("7357a6db-e153-4e7b-9a8c-ccd8c3356d7a"),
                            Caption = "Chili Peppers",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("a7008f60-5e24-4b35-b7b3-f18c68c9ecf9"),
                            Caption = "Jalapenos",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("9ff1df1b-3953-4671-80db-a66883866aa4"),
                            Caption = "Habaneros",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("6b335cc4-7efa-4a9f-8dfc-6b5145e085b1"),
                            Caption = "Serrano Peppers",
                            IsDeleted = false,
                            SubCategoryId = new Guid("66508192-19fd-47a6-b910-c31fc6d0973f")
                        },
                        new
                        {
                            Id = new Guid("d222558d-489e-4716-b33d-f5b5b2b9f564"),
                            Caption = "Ground Beef",
                            IsDeleted = false,
                            SubCategoryId = new Guid("9d7fff01-9e87-436d-9761-bfcc9cc4ad5a")
                        },
                        new
                        {
                            Id = new Guid("8e19f6a9-74c5-4aa5-a1c6-3c307215d342"),
                            Caption = "Steaks",
                            IsDeleted = false,
                            SubCategoryId = new Guid("9d7fff01-9e87-436d-9761-bfcc9cc4ad5a")
                        },
                        new
                        {
                            Id = new Guid("60b40aa6-fa2a-46dc-ab16-c6db47e6fda8"),
                            Caption = "Roasts",
                            IsDeleted = false,
                            SubCategoryId = new Guid("9d7fff01-9e87-436d-9761-bfcc9cc4ad5a")
                        },
                        new
                        {
                            Id = new Guid("536ee163-d07c-400f-80ac-ccc3d21e77da"),
                            Caption = "Pork Chops",
                            IsDeleted = false,
                            SubCategoryId = new Guid("ac14dc1d-fa3c-4e9f-bdc8-62ad10b687c7")
                        },
                        new
                        {
                            Id = new Guid("07625ebb-3473-4e27-9239-a249f1597945"),
                            Caption = "Pork Loins",
                            IsDeleted = false,
                            SubCategoryId = new Guid("ac14dc1d-fa3c-4e9f-bdc8-62ad10b687c7")
                        },
                        new
                        {
                            Id = new Guid("8c40056e-45b1-4b56-a62c-1003ba243db5"),
                            Caption = "Ground Pork",
                            IsDeleted = false,
                            SubCategoryId = new Guid("ac14dc1d-fa3c-4e9f-bdc8-62ad10b687c7")
                        },
                        new
                        {
                            Id = new Guid("7e60eea9-f4a4-4a2c-972b-3d05a1872906"),
                            Caption = "Bacon",
                            IsDeleted = false,
                            SubCategoryId = new Guid("ac14dc1d-fa3c-4e9f-bdc8-62ad10b687c7")
                        },
                        new
                        {
                            Id = new Guid("3dfe13b1-dea1-412a-8f67-1f4c4066d2d4"),
                            Caption = "Ham",
                            IsDeleted = false,
                            SubCategoryId = new Guid("ac14dc1d-fa3c-4e9f-bdc8-62ad10b687c7")
                        },
                        new
                        {
                            Id = new Guid("7fcc9b55-c79c-4bc3-8917-c2a13e1fae9b"),
                            Caption = "Chicken Breasts",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1c9f7178-9f48-4383-a7d8-52b3c4a2eba5")
                        },
                        new
                        {
                            Id = new Guid("3bce823b-517d-48f8-8859-475ffbe5c187"),
                            Caption = "Chicken Thighs",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1c9f7178-9f48-4383-a7d8-52b3c4a2eba5")
                        },
                        new
                        {
                            Id = new Guid("13c9dbf6-82b1-472b-a91b-4f22c9927a19"),
                            Caption = "Chicken Wings",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1c9f7178-9f48-4383-a7d8-52b3c4a2eba5")
                        },
                        new
                        {
                            Id = new Guid("d922d149-7f7e-4d33-a2d3-c5783e179db8"),
                            Caption = "Ground Chicken",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1c9f7178-9f48-4383-a7d8-52b3c4a2eba5")
                        },
                        new
                        {
                            Id = new Guid("a4903769-a86f-4d04-966d-2ca3c7ab0a7d"),
                            Caption = "Salmon",
                            IsDeleted = false,
                            SubCategoryId = new Guid("317cabed-f827-4117-88ab-579730269b54")
                        },
                        new
                        {
                            Id = new Guid("649ff6d8-735a-4284-8572-e2214c4fd233"),
                            Caption = "Tuna",
                            IsDeleted = false,
                            SubCategoryId = new Guid("317cabed-f827-4117-88ab-579730269b54")
                        },
                        new
                        {
                            Id = new Guid("72bcc391-6646-4931-a838-7641513db122"),
                            Caption = "Cod",
                            IsDeleted = false,
                            SubCategoryId = new Guid("317cabed-f827-4117-88ab-579730269b54")
                        },
                        new
                        {
                            Id = new Guid("ba1ef009-7c17-40d5-8baa-48ab47fcd8c2"),
                            Caption = "Haddock",
                            IsDeleted = false,
                            SubCategoryId = new Guid("317cabed-f827-4117-88ab-579730269b54")
                        },
                        new
                        {
                            Id = new Guid("347eabf5-3a6c-4d41-8de3-e3d4ee20067e"),
                            Caption = "Shrimp",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1b26e890-6f81-4e22-9763-301ff482e6f3")
                        },
                        new
                        {
                            Id = new Guid("2fe1e3b7-315e-4569-9e78-559dd62c208c"),
                            Caption = "Crab",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1b26e890-6f81-4e22-9763-301ff482e6f3")
                        },
                        new
                        {
                            Id = new Guid("e2faa565-fd81-4c65-b1f2-ec794e05ea3a"),
                            Caption = "Lobster",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1b26e890-6f81-4e22-9763-301ff482e6f3")
                        },
                        new
                        {
                            Id = new Guid("629505a3-e234-4249-8ab7-57d40b973501"),
                            Caption = "Scallops",
                            IsDeleted = false,
                            SubCategoryId = new Guid("1b26e890-6f81-4e22-9763-301ff482e6f3")
                        },
                        new
                        {
                            Id = new Guid("6ddf6949-e764-4a11-b47c-a5041e60c40b"),
                            Caption = "Cheddar",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("61714b28-2e35-407a-babb-37b7410f8862"),
                            Caption = "Mozzarella",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("589a28df-6cd1-4dae-b4b2-4d6bb9a548a6"),
                            Caption = "Swiss",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("f1eeaf08-8168-4284-9369-380ab4576233"),
                            Caption = "Parmesan",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("d3ae0655-5a7d-4d74-b2d1-1a191d8dbd92"),
                            Caption = "Feta",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("28c58156-3cbf-4d3e-b3ee-ef5914351203"),
                            Caption = "Goat Cheese",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("2ad061f7-1ca2-4ced-913d-e0fb5c5adf69"),
                            Caption = "Cottage Cheese",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("45ff41f3-c81a-4362-98f5-b6f062fda958"),
                            Caption = "Ricotta",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("e983c2f0-5672-4e23-97d8-394bf3882f3e"),
                            Caption = "Cream Cheese",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("5f4ea4bb-2cb6-441b-97f1-39e36c7cffa7"),
                            Caption = "Brie",
                            IsDeleted = false,
                            SubCategoryId = new Guid("3d16103f-43cc-499b-b9eb-ece0a502fecc")
                        },
                        new
                        {
                            Id = new Guid("7bfaf7bc-b6eb-42e3-b894-cdca1261d57b"),
                            Caption = "Whole Milk",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f8ccc5ab-4e8e-4be9-9978-747aa19968eb")
                        },
                        new
                        {
                            Id = new Guid("a6466296-90d3-4247-8722-a276ca983a6d"),
                            Caption = "Low-Fat Milk",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f8ccc5ab-4e8e-4be9-9978-747aa19968eb")
                        },
                        new
                        {
                            Id = new Guid("b0c46b17-84cf-4c1c-a0a6-deaff255b53d"),
                            Caption = "Skim Milk",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f8ccc5ab-4e8e-4be9-9978-747aa19968eb")
                        },
                        new
                        {
                            Id = new Guid("5fc2812e-e856-402a-905a-96a4fb4b81be"),
                            Caption = "Greek Yogurt",
                            IsDeleted = false,
                            SubCategoryId = new Guid("5bdf8914-ba06-4415-b018-09a41edf26fd")
                        },
                        new
                        {
                            Id = new Guid("9666d9df-9924-4a6c-8edc-a51a771c54b8"),
                            Caption = "Salted Butter",
                            IsDeleted = false,
                            SubCategoryId = new Guid("5bdf8914-ba06-4415-b018-09a41edf26fd")
                        },
                        new
                        {
                            Id = new Guid("0a63777c-0fce-4b45-bae8-ed78743ac91c"),
                            Caption = "Unsalted Butter",
                            IsDeleted = false,
                            SubCategoryId = new Guid("5bdf8914-ba06-4415-b018-09a41edf26fd")
                        },
                        new
                        {
                            Id = new Guid("180389f0-de08-4cc4-a048-2475b712266e"),
                            Caption = "Heavy Cream",
                            IsDeleted = false,
                            SubCategoryId = new Guid("5bdf8914-ba06-4415-b018-09a41edf26fd")
                        },
                        new
                        {
                            Id = new Guid("b59a056a-43a3-4bcb-81d9-a23b2120a077"),
                            Caption = "Sour Cream",
                            IsDeleted = false,
                            SubCategoryId = new Guid("5bdf8914-ba06-4415-b018-09a41edf26fd")
                        },
                        new
                        {
                            Id = new Guid("3eb107b3-915a-4302-b07a-b3f264e6d98d"),
                            Caption = "White Rice",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4f55fb5c-7117-4911-b481-48a75141c85e")
                        },
                        new
                        {
                            Id = new Guid("f1667388-791b-43cf-8a94-22ee61eccba9"),
                            Caption = "Brown Rice",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4f55fb5c-7117-4911-b481-48a75141c85e")
                        },
                        new
                        {
                            Id = new Guid("89e1cc83-230c-42b2-9227-073b2b66bf91"),
                            Caption = "Basmati Rice",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4f55fb5c-7117-4911-b481-48a75141c85e")
                        },
                        new
                        {
                            Id = new Guid("2c3775d4-d60c-4532-8f04-1564aeab615c"),
                            Caption = "Jasmine Rice",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4f55fb5c-7117-4911-b481-48a75141c85e")
                        },
                        new
                        {
                            Id = new Guid("0642bc98-2980-4046-b8d8-6c9acbe43c74"),
                            Caption = "Arborio Rice",
                            IsDeleted = false,
                            SubCategoryId = new Guid("4f55fb5c-7117-4911-b481-48a75141c85e")
                        },
                        new
                        {
                            Id = new Guid("318c2189-76b7-4e7c-b2da-d8c670c1f78e"),
                            Caption = "Quinoa",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37")
                        },
                        new
                        {
                            Id = new Guid("fa9ceb65-99d7-4f50-897b-495aee237b0f"),
                            Caption = "Barley",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37")
                        },
                        new
                        {
                            Id = new Guid("5a968207-b687-40d7-8102-310d4d8a3cb8"),
                            Caption = "Millet",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37")
                        },
                        new
                        {
                            Id = new Guid("04040a01-febf-46d9-b75a-25f865265261"),
                            Caption = "Buckwheat",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37")
                        },
                        new
                        {
                            Id = new Guid("e3e222ed-cbeb-4be0-97f3-1bd667dfb9ac"),
                            Caption = "Rye",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37")
                        },
                        new
                        {
                            Id = new Guid("8d67170b-538b-4442-9848-a68b3113039f"),
                            Caption = "Cornmeal",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37")
                        },
                        new
                        {
                            Id = new Guid("58517d3e-9dab-4e2d-ac1a-fa308c8830ec"),
                            Caption = "Polenta",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f9c1d277-5dc6-46ae-87d6-b1b66e44bc37")
                        },
                        new
                        {
                            Id = new Guid("8679a1ca-7fc6-4103-9e8b-1a9c66454c5a"),
                            Caption = "Spaghetti",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("50370d9e-0cf8-47e6-b362-2501abd21ecb"),
                            Caption = "Penne",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("e3183717-5cb5-4497-b009-8184fe01983b"),
                            Caption = "Fusilli",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("1201790a-adab-4c42-9b36-c0670ed3f380"),
                            Caption = "Macaroni",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("6136f988-679f-42a6-9304-4e4e1a0e9315"),
                            Caption = "Lasagna Sheets",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("4b982f0e-e8d2-45a0-96c8-0c3c6ff32c5b"),
                            Caption = "Rice Noodles",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("8e5d5497-7e5b-4fec-97ee-5f87ace3723d"),
                            Caption = "Soba Noodles",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("773cfcff-2f46-446d-8f8a-38b2a76aca61"),
                            Caption = "Egg Noodles",
                            IsDeleted = false,
                            SubCategoryId = new Guid("692b49bf-17da-4d08-b8e6-a863d571cc5c")
                        },
                        new
                        {
                            Id = new Guid("4787a327-dd76-489c-81ac-c0bdb49c2db7"),
                            Caption = "Black Beans",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f5d6dae7-80a7-45ec-8995-cbe47452a12b")
                        },
                        new
                        {
                            Id = new Guid("52d9b842-df1d-4e42-b4b1-aa177d39539e"),
                            Caption = "Kidney Beans",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f5d6dae7-80a7-45ec-8995-cbe47452a12b")
                        },
                        new
                        {
                            Id = new Guid("9d760ed4-c37c-4c6c-8a94-f1c9dba21bce"),
                            Caption = "Pinto Beans",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f5d6dae7-80a7-45ec-8995-cbe47452a12b")
                        },
                        new
                        {
                            Id = new Guid("196faa87-b84a-4998-b7c7-693534f65f19"),
                            Caption = "Chickpeas",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f5d6dae7-80a7-45ec-8995-cbe47452a12b")
                        },
                        new
                        {
                            Id = new Guid("ba8d6087-4540-4b2f-ba22-ae94f03f04c3"),
                            Caption = "Lentils",
                            IsDeleted = false,
                            SubCategoryId = new Guid("f5d6dae7-80a7-45ec-8995-cbe47452a12b")
                        },
                        new
                        {
                            Id = new Guid("34f3492c-60e3-4539-bc78-3701a58ef47d"),
                            Caption = "Almonds",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b")
                        },
                        new
                        {
                            Id = new Guid("cd863d6a-7145-4f3c-9fcf-2e0f0087c5d5"),
                            Caption = "Walnuts",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b")
                        },
                        new
                        {
                            Id = new Guid("f02dc182-155c-4a65-9468-ed3c707bcb24"),
                            Caption = "Pecans",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b")
                        },
                        new
                        {
                            Id = new Guid("ab8af64e-364f-48fb-bd5a-9a5b316b2f3a"),
                            Caption = "Cashews",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b")
                        },
                        new
                        {
                            Id = new Guid("81ed9326-aa76-4d42-a32a-31e65c63f1fe"),
                            Caption = "Pistachios",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b")
                        },
                        new
                        {
                            Id = new Guid("f40c6732-7c7c-4bd1-84e1-9ff41f71ff22"),
                            Caption = "Macadamia Nuts",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b")
                        },
                        new
                        {
                            Id = new Guid("4a3099c9-de6b-4bb4-92f2-9e9da7312875"),
                            Caption = "Peanuts",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fd2acf2c-7d94-47f6-ad84-db76e2726b0b")
                        },
                        new
                        {
                            Id = new Guid("b4563c76-17d1-43b3-83b3-84d978d9fed0"),
                            Caption = "Sunflower Seeds",
                            IsDeleted = false,
                            SubCategoryId = new Guid("8378c940-b7ee-41a0-b740-fc7dcb62729d")
                        },
                        new
                        {
                            Id = new Guid("d33e7046-a6f2-4bb7-83b0-cc9c38effade"),
                            Caption = "Pumpkin Seeds",
                            IsDeleted = false,
                            SubCategoryId = new Guid("8378c940-b7ee-41a0-b740-fc7dcb62729d")
                        },
                        new
                        {
                            Id = new Guid("29719ece-6a43-4979-8815-a5fd9be80126"),
                            Caption = "Chia Seeds",
                            IsDeleted = false,
                            SubCategoryId = new Guid("8378c940-b7ee-41a0-b740-fc7dcb62729d")
                        },
                        new
                        {
                            Id = new Guid("6ca18038-d433-45e3-8047-c6312fbeb8c0"),
                            Caption = "Flaxseeds",
                            IsDeleted = false,
                            SubCategoryId = new Guid("8378c940-b7ee-41a0-b740-fc7dcb62729d")
                        },
                        new
                        {
                            Id = new Guid("e01978cc-e0aa-4bba-9d3b-cc5f8816fc40"),
                            Caption = "Olive Oil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f")
                        },
                        new
                        {
                            Id = new Guid("1d8f452f-1f4b-434a-9053-363b6896df8f"),
                            Caption = "Vegetable Oil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f")
                        },
                        new
                        {
                            Id = new Guid("84a3bbb1-6583-4226-9ddf-64e7a389ffd5"),
                            Caption = "Canola Oil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f")
                        },
                        new
                        {
                            Id = new Guid("8b8d9a34-8669-4842-8956-08eb336a7687"),
                            Caption = "Sunflower Oil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f")
                        },
                        new
                        {
                            Id = new Guid("4a4b0def-d116-4a60-a502-e24153595369"),
                            Caption = "Coconut Oil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f")
                        },
                        new
                        {
                            Id = new Guid("78dd3bad-752f-4f27-ae8e-d3b8472a1fd5"),
                            Caption = "Avocado Oil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f")
                        },
                        new
                        {
                            Id = new Guid("a31b5a2b-3ba8-490c-8b51-0e114968a2cf"),
                            Caption = "Sesame Oil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("6ca003f3-9a93-4d0f-9e58-808b9426b94f")
                        },
                        new
                        {
                            Id = new Guid("bc7b6069-a86c-4602-8c69-8279dda3d449"),
                            Caption = "Basil",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("3fb9450c-5941-446b-9609-cf6cb574955a"),
                            Caption = "Oregano",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("7765bca7-cb6e-4588-bcbb-811d7edcecfc"),
                            Caption = "Thyme",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("db977dad-11e2-4ca6-ae96-7ca393347642"),
                            Caption = "Rosemary",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("e365939a-c217-4201-b29b-b1627aac40c4"),
                            Caption = "Parsley",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("cc96ca2e-4eba-4a23-8339-5c3738a757ac"),
                            Caption = "Cilantro",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("680a2262-728b-4dfd-8ff6-5371a98b99df"),
                            Caption = "Dill",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("872d12f4-d8f7-4200-a5f8-be951741dc4d"),
                            Caption = "Mint",
                            IsDeleted = false,
                            SubCategoryId = new Guid("35c5e37f-17f5-4ff1-9ea9-6ae79b4bb2d8")
                        },
                        new
                        {
                            Id = new Guid("00979c3f-37d0-44d2-bd11-bfa3acd8ed44"),
                            Caption = "Black Pepper",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("0b6966e5-89c8-44a6-82e9-bd5a965a8357"),
                            Caption = "Paprika",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("4b44eb65-626a-45c3-ba9c-b4d9125cacc3"),
                            Caption = "Chili Powder",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("26ae5673-a6aa-4df1-b2c2-b5debb429cf9"),
                            Caption = "Cumin",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("5c209517-d906-485d-9da9-21d4a2db5bfc"),
                            Caption = "Coriander",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("778a0e4a-fdd9-4177-bb3d-dc64c22abf4a"),
                            Caption = "Turmeric",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("5747ffdd-5df1-49cc-ad27-b0717891410b"),
                            Caption = "Cinnamon",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("7e985f3f-43bc-4ac7-af11-50ecc74a3e7d"),
                            Caption = "Ginger",
                            IsDeleted = false,
                            SubCategoryId = new Guid("7893cddc-a4f2-4ee2-bc52-84456a5b2f28")
                        },
                        new
                        {
                            Id = new Guid("262c454d-18f4-4ac0-9bc5-8d1b4a148d12"),
                            Caption = "Granulated Sugar",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d133f302-ec57-4acb-845c-eb0daea1b6de")
                        },
                        new
                        {
                            Id = new Guid("6862340a-71b7-492f-8a72-dd8059376fc9"),
                            Caption = "Brown Sugar",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d133f302-ec57-4acb-845c-eb0daea1b6de")
                        },
                        new
                        {
                            Id = new Guid("bad18ba4-2959-4e84-9279-e51eede64f67"),
                            Caption = "Honey",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d133f302-ec57-4acb-845c-eb0daea1b6de")
                        },
                        new
                        {
                            Id = new Guid("62de3b4c-076b-4ce7-abc1-9cbdb332c04e"),
                            Caption = "Maple Syrup",
                            IsDeleted = false,
                            SubCategoryId = new Guid("d133f302-ec57-4acb-845c-eb0daea1b6de")
                        },
                        new
                        {
                            Id = new Guid("45ca4109-1f41-48fb-ad6e-a7c70ec21060"),
                            Caption = "Salt",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fb7a6e78-1351-4992-a732-1b4f8510dcb9")
                        },
                        new
                        {
                            Id = new Guid("9e1b127a-dd74-4122-8cad-c116d736669f"),
                            Caption = "Baking Powder",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fb7a6e78-1351-4992-a732-1b4f8510dcb9")
                        },
                        new
                        {
                            Id = new Guid("fec43808-4d01-4693-a15c-122ab4d65de1"),
                            Caption = "Baking Soda",
                            IsDeleted = false,
                            SubCategoryId = new Guid("fb7a6e78-1351-4992-a732-1b4f8510dcb9")
                        });
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Recipe.FoodRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<string>("CookingInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Recipe.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FoodRecipeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MeasurmentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodRecipeId");

                    b.HasIndex("ProductId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.UserProfile.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("65404861-db2c-43cc-8001-4be14a2aa46f"),
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = new Guid("c9259576-0ab7-467f-be68-5436e5301e0b"),
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = new Guid("f40b0b39-f708-4ae2-ace5-bb3be36b0fd8"),
                            Name = "Peanuts"
                        },
                        new
                        {
                            Id = new Guid("ca1311f2-2e82-417f-9ca2-ef305c3fb529"),
                            Name = "Tree Nuts"
                        },
                        new
                        {
                            Id = new Guid("73ff93ea-55bd-4c55-8711-f8806686286b"),
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = new Guid("a8ff2732-c9e3-4f2d-8c9e-880370538a41"),
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = new Guid("5fb7ffd1-2795-4e37-be01-89ab5173b789"),
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("d3dd8f8b-a096-4e2a-b89d-f356e2319500"),
                            Name = "Soy"
                        },
                        new
                        {
                            Id = new Guid("6080ac5c-29b3-404b-8f21-6ecaa9828ca5"),
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = new Guid("e6b9fbf8-195a-41d9-a11d-ced3f1a75f12"),
                            Name = "Sesame"
                        });
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.UserProfile.KitchenEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KitchenEquipments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e37b52b4-0df7-47ce-8eb8-cf111897cb9b"),
                            Name = "Blender"
                        },
                        new
                        {
                            Id = new Guid("5f48d79c-08e1-434e-8cfb-160b4954bf4a"),
                            Name = "Oven"
                        },
                        new
                        {
                            Id = new Guid("d5e53f81-1d34-4314-bd01-668cb2c9ba32"),
                            Name = "Microwave"
                        },
                        new
                        {
                            Id = new Guid("d4dbb194-6188-4ac3-8098-946fca616af1"),
                            Name = "Air Fryer"
                        },
                        new
                        {
                            Id = new Guid("dacfa5ba-1abf-4107-a1b5-531b0fb86a95"),
                            Name = "Food Processor"
                        },
                        new
                        {
                            Id = new Guid("ea2f0364-5631-4c59-9f35-dc46a2a91058"),
                            Name = "Grill"
                        },
                        new
                        {
                            Id = new Guid("f0f62b17-5a3b-407a-9d1b-812adcb30a1b"),
                            Name = "Stove"
                        },
                        new
                        {
                            Id = new Guid("f8eb9aea-e8b5-4737-b1ff-5914738abf1c"),
                            Name = "Slow Cooker"
                        },
                        new
                        {
                            Id = new Guid("efc8788b-0dde-40a4-a7a2-3c43d56cf3ef"),
                            Name = "Pressure Cooker"
                        },
                        new
                        {
                            Id = new Guid("49bcd407-62f6-4e8f-b00e-84d47cfdc33e"),
                            Name = "Toaster"
                        },
                        new
                        {
                            Id = new Guid("bcd234bb-e846-4935-85cf-f30cc296daa9"),
                            Name = "Rice Cooker"
                        },
                        new
                        {
                            Id = new Guid("4efc2b40-013b-4ac6-aed9-a976a2888b31"),
                            Name = "Mixer"
                        });
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("BirthdayDate")
                        .HasColumnType("date");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DietGoalType")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("AllergyUserProfile", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.UserProfile.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriWise.Domain.Entities.UserProfile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenEquipmentUserProfile", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.UserProfile.KitchenEquipment", null)
                        .WithMany()
                        .HasForeignKey("KitchenEquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriWise.Domain.Entities.UserProfile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriWise.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Product.FoodSubCategory", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Product.FoodCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Product.Product", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Product.FoodSubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Recipe.RecipeIngredient", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Recipe.FoodRecipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodRecipeId");

                    b.HasOne("NutriWise.Domain.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.UserProfile.UserProfile", b =>
                {
                    b.HasOne("NutriWise.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Product.FoodCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("NutriWise.Domain.Entities.Recipe.FoodRecipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
