/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CallbackGoogle: typeof import('./src/components/Google/CallbackGoogle.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    LoginButton: typeof import('./src/components/Google/LoginButton.vue')['default']
    MealPlan: typeof import('./src/components/MealPlan/MealPlan.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
